-- Text
vim.cmd("hi Normal guibg=#efefef guifg=#000000 ctermbg=NONE")
vim.cmd("hi NormalFloat guibg=#efefef guifg=#000000 ctermbg=NONE")
vim.cmd("hi Pmenu guibg=#efefef guifg=#000000")
vim.cmd("hi @keyword.import guifg=#0020ff gui=bold")
vim.cmd("hi PreProc guifg=#0020ff gui=bold")
vim.cmd("hi Define guifg=#0020ff gui=bold")
vim.cmd("hi @keyword.directive guifg=#0020ff gui=bold")
vim.cmd("hi @keyword.repeat guifg=#00aa00 gui=bold")
vim.cmd("hi @keyword.conditional guifg=#ff2000 gui=bold")
vim.cmd("hi DiagnosticUnderlineWarn guifg=#ff2000 gui=bold")
vim.cmd("hi WarningMsg guifg=#ff2000 gui=bold")
vim.cmd("hi @comment.warning guifg=#ff2000 gui=bold")
vim.cmd("hi LspReferenceWrite guifg=#ff2000 gui=bold")
vim.cmd("hi LspReferenceRead guifg=#ff2000 gui=bold")
vim.cmd("hi LspReferenceText guifg=#ff2000 gui=bold")
vim.cmd("hi DiagnosticInfo guifg=#ff2000 gui=bold")
vim.cmd("hi DiagnosticWarn guifg=#ff2000 gui=bold")
vim.cmd("hi DiagnosticOk guifg=#ff2000 gui=bold")
vim.cmd("hi DiagnosticHint guifg=#ff2000 gui=bold")
vim.cmd("hi DiagnosticError guifg=#ff2000 gui=bold")
vim.cmd("hi Diagnostic guifg=#ff2000 gui=bold")
vim.cmd("hi MoreMsg guifg=#ff2000 gui=bold")
vim.cmd("hi ErrorMsg guifg=#ff2000 gui=bold")
vim.cmd("hi ModeMsg guifg=#ff2000 gui=bold")
vim.cmd("hi QuickFixLine guifg=#ff2000 gui=bold")
vim.cmd("hi Directory guifg=#ff2000 gui=bold")
vim.cmd("hi @keyword.return guifg=#aa00ff gui=bold")
vim.cmd("hi Macro guifg=#000000")
vim.cmd("hi Include guifg=#0020ff gui=bold")
vim.cmd("hi function guifg=#ff8020 gui=bold")
vim.cmd("hi Special guifg=#aa00ff gui=bold")
vim.cmd("hi Variable guifg=#000000")
vim.cmd("hi Statement guifg=#000000")
vim.cmd("hi Keyword guifg=#aa00ff")
vim.cmd("hi Type guifg=#aa00ff gui=bold")
vim.cmd("hi Operator guifg=#000000 gui=bold")
vim.cmd("hi Number guifg=#000000")
vim.cmd("hi Constant guifg=#aa0044 gui=bold")
vim.cmd("hi Boolean guifg=#000000 gui=bold")
vim.cmd("hi Identifier guifg=#000000")
vim.cmd("hi Title guifg=#000000")
vim.cmd("hi Question guifg=#000000")
vim.cmd("hi String guifg=#0020ff")
vim.cmd("hi Character guifg=#0020ff")
vim.cmd("hi Comment guifg=#00aa00 gui=italic")
vim.cmd("hi Delimiter guifg=#000000")
vim.cmd("hi @variable guifg=#000000")
vim.cmd("hi Structure guifg=#00aa00 gui=bold")
vim.cmd("hi ColorColumn guibg=#e5e5e5")

vim.cmd("hi MatchParen guifg=#ffffff guibg=#0020ff gui=bold")
-- Line
vim.cmd("hi CursorLineNR guibg=NONE guifg=NONE")
vim.cmd("hi CursorLine guibg=#e5e5e5")

vim.cmd("hi SignColumn guibg=#e5e5e5")
vim.cmd("hi Statusline guibg=#000000 guifg=#ff8020")
vim.cmd("hi StatuslineNC guibg=#888888 guifg=#cccccc")


--NvimTree
vim.cmd("hi NvimTreeNormalFloat guibg=NONE guifg=NONE")
vim.cmd("hi NvimTreeNormalFloatBorder guibg=NONE guifg=NONE")
vim.cmd("hi NvimTreeFolderName guibg=NONE guifg=#ff8020 gui=bold")
vim.cmd("hi NvimTreeOpenedFolderName guibg=NONE guifg=#ff0000 gui=bold")
vim.cmd("hi NvimTreeRootFolder guibg=NONE guifg=#0020ff gui=bold")

vim.cmd("hi WhichKeyNormal guibg=#c5c5c5 guifg=NONE")
vim.cmd("hi NvimTreePopUp guibg=NONE guifg=NONE")
